[package]
name = "chat_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bincode = "3.0.0"
quinn = "0.11.9"
rcgen = "0.14.6"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
